---
## tasks file for practice

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

##
- name: Disable firewalld
  ansible.builtin.systemd_service:
    name: firewalld.service
    state: stopped
    enabled: false

##
- name: backing up the original if it differs from the copied version
  ansible.builtin.copy:
    src: /etc/chrony.conf
    dest: /etc/chrony.conf_bkp
    remote_src: yes
- name: Copy chrony.conf file into place
  ansible.builtin.copy:
    src: chrony.conf
    dest: /etc/chrony.conf
  register: chrony_conf  
- name: Restart service chrony
  ansible.builtin.systemd_service:
    name: chronyd.service
    state: restarted
    daemon_reload: true
  when: chrony_conf.changed 

##
- name: Upload repo
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/

##
- name: Install docker
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
- name: Docker start enable
  ansible.builtin.systemd_service:
    name: docker.service
    state: started
    enabled: true
- name: Ensure required Python library packaging is installed
  ansible.builtin.pip:
    name: packaging
    state: present
- name: Verify Python packaging installation
  ansible.builtin.command:
    cmd: python3 -m pip install packaging
  register: packaging_check
  changed_when: false
- name: Verify Python packaging installation2
  ansible.builtin.command:
    cmd: python3 -m pip install requests
  register: packaging_check
  changed_when: false
